### PR TITLE
Enhance flake

### PR DESCRIPTION
**Pull request by oluceps**
## Description
+ Finish nix build

This branch has synced with the master.

```
cd eunomia-bpf/examples/bpftools/minimal
nix run github:oluceps/eunomia-bpf/nix-build#ecc -- ./minimal.bpf.c
```

bundle also works.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by oluceps** [comment]
Hi @undefined-moe , could you please take a look at this pr? If there is no issue, you could do a rebase & merge so that we can merge these changes into the master by https://github.com/eunomia-bpf/eunomia-bpf/pull/261.

**Comment by undefined-moe** [comment]
I see a lot of irrelevant modifications here (for example `.github/ISSUE_TEMPLATE`). Could you please double-check? There shouldn't be so many changed files as I've just synced from upstream.

**Comment by oluceps** [comment]
> I see a lot of irrelevant modifications here (for example `.github/ISSUE_TEMPLATE`). Could you please double-check? There shouldn't be so many changed files as I've just synced from upstream.

(`.github/ISSUE_TEMPLATE` is contained by one of my modifications.

I think those extra diffs are caused by a merge using GitHub web.
You can try the below:

1. At your local repository, in `bundle` branch, pull from github remote repo with `git pull`.
2. Hard reset to `3d21903e532f455d3594ec954be462c891807fe1` with cmd `git reset 3d21903 --hard`, this will reset the Merge message, which is generated by github merging.
3. Do a force push with `git push origin bundle --force-with-lease`.

Hope this will be helpful~

**Comment by oluceps** [comment]
If the above doesn't work you can try hard reset to `de50cd216903c8ad0324491715f724384a5af208` and do a rebase to master ~HEAD of eunomia-bpf:
1. `git remote add upstream https://github.com/eunomia-bpf/eunomia-bpf.git`
2. `git fetch upstream master`
3. `git rebase upstream/master` This will rebase and place your commit in bundle `HEAD` and make history consistent with eunomia-bpf repo.
4. `git push origin bundle --force-with-lease`

**Comment by undefined-moe** [comment]
git cli works, testing on it. btw I think it's not a good practice to put two things into a single pull request (issue_template and nix), might be better to create another pull req to the upstream

**Comment by oluceps** [comment]
> btw I think it's not a good practice to put two things into a single pull request (issue_template and nix), might be better to create another pull req to the upstream

I agree with that. This commit has been reset and will commit on another pr.

**Comment by oluceps** [comment]
You could directly try the [second suggestion](https://github.com/undefined-moe/eunomia-bpf/pull/1#issuecomment-1758794137), bcz I think the 1st one may not enough solve this.

**Comment by undefined-moe** [comment]
works, merged

**Comment by oluceps** [comment]
Thanks! <3

**Pull request merged**
